# Generated by Django 3.2.6 on 2021-08-29 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_toy'),
    ]

    operations = [
        migrations.AddField(
            model_name='pup',
            name='toys',
            field=models.ManyToManyField(to='main_app.Toy'),
        ),
    ]
